//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qna.Models.DataModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Qna.Models.DataModels;
    
    public partial class QnaDBEntities : DbContext
    {
        public QnaDBEntities()
            : base("name=QnaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<CategoryView>().HasKey(t => t.Id).ToTable(nameof(CategoryView));
            modelBuilder.Entity<UserView>().HasKey(t => t.Id).ToTable(nameof(UserView));
            modelBuilder.Entity<AnswerView>().HasKey(t => t.Id).ToTable(nameof(AnswerView));
            modelBuilder.Entity<QuestionView>().HasKey(t => t.Id).ToTable(nameof(QuestionView));
            //throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<ANSWER> ANSWERs { get; set; }
        public virtual DbSet<CATEGEORY> CATEGEORies { get; set; }
        public virtual DbSet<LIKED> LIKEDs { get; set; }
        public virtual DbSet<QUESTION> QUESTIONs { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
        public virtual DbSet<VIEWED> VIEWEDs { get; set; }
        public virtual DbSet<VOTED> VOTEDs { get; set; }
        public virtual DbSet<AnswerView> AnswerViews { get; set; }
        public virtual DbSet<CategoryView> CategoryViews { get; set; }
        public virtual DbSet<QuestionView> QuestionViews { get; set; }
        public virtual DbSet<UserView> UserViews { get; set; }
    }
}
