//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qna.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUESTION
    {
        public int Id { get; set; }
        public Nullable<int> QuestionedBy { get; set; }
        public string Statement { get; set; }
        public string Description { get; set; }
        public Nullable<int> CategeoryId { get; set; }
        public Nullable<System.DateTime> QuestionedOn { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> IsResolved { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    }
}
