//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qna.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserView
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
        public string Department { get; set; }
        public string Location { get; set; }
        public string proPicUrl { get; set; }
        public Nullable<int> questionsAsked { get; set; }
        public Nullable<int> questionsAnswered { get; set; }
        public Nullable<int> questionsSolved { get; set; }
        public Nullable<int> likes { get; set; }
        public Nullable<int> dislikes { get; set; }
    }
}
